### PR TITLE
Add support for toggling Service Worker related preferences

### PR DESCRIPTION
**Pull request by azasypkin**
Hey @julienw, tell me if you don't mind to incorporate this change into your tool? :) I'm using this locally intensively these days, so was thinking it maybe useful.

Thanks!

### CODE REVIEW

**Comment by azasypkin** [comment]
Hey @julienw, just ping, tell me if you think it's not the right place for this PR :)

**Comment by julienw** [comment]
It is, I'm just lagging a lot reading my mails !

**Comment by julienw** [comment]
landed in 326260cb328a03f83efaa1bcaf39212afbaefddc (I added the new commands in the help line)

**Comment by azasypkin** [comment]
\0/

**Pull request closed without merging**
